language: node_js
sudo: false
node_js:
  - stable
script:
  - npm run ci
services:
  - postgresql
after_success:
  - npm run cov:report
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
